name: Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  push_node_image:
    name: Push node image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: auvred/devcon:latest
          context: "{{defaultContext}}:node"
          push: true

  push_rest_images:
    name: Push rest images
    needs: push_node_image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        tag: [devops, rust]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: auvred/devcon:${{ matrix.tag }}
          context: "{{defaultContext}}:${{ matrix.tag }}"
          push: true
